---
# tasks file for galaxyproject.pulsar

# Deploy a Pulsar server
#   http://pulsar.readthedocs.org/

# COPIED FROM GALAXY
# To my knowledge there is no other way to know whether or not the consumer of
# this role has set `become: true` outside this role, and `become: {{ foo |
# default(omit) }}` on a task/block actually clobbers the higher level use of
# `become`. This is a temporary solution.

- name: Set privilege separation default variables
  set_fact:
    __pulsar_remote_user: "{{ ansible_user_id | default(omit) }}"
    __pulsar_become: "{{ ansible_env.SUDO_USER is defined }}"
    __pulsar_become_user: "{{ ansible_user_id | default(omit) }}"

- name: Include user creation tasks
  include_tasks: user.yml
  when: pulsar_create_user or pulsar_create_privsep_user

- name: Include path management tasks
  include_tasks: paths.yml

- name: Include virtualenv setup tasks
  include_tasks: virtualenv.yml
  when: pulsar_install_virtualenv

- name: Include config files tasks
  include_tasks: configure.yml

- include_tasks: systemd.yml
  when: pulsar_systemd
